### ISSUE TITLE
Server URL without domain level

### ISSUE THREAD

**Issue by diegofcv** [mchugh19/zabbix-vue#15]
Hi,
I'd love to use the extension, but I see that configuration is unable to accept an URL address that lacks an extension or domain level. I mean, I cannot configure the Zabbix URL like "www-zabbix", only with something like "www-zabbix.xpto". Would it be possible to avoid that?
Thanks! Congrats!
DiegoV

**Comment by mchugh19** [comment]
Hmm, that's true. The domain validation currently requires a dot spaced domain name. I'll make a release that removes the validation, and in the meantime you can use an IP address for testing.

**Comment by mchugh19** [comment]
This was completed with 1.0.8/9 (the bump to .9 was only to update an incorrect translation name)
