### ISSUE TITLE
Zabbix shows as happy and no problems when unable to connect

### ISSUE THREAD

**Issue by RedXIV2** [mchugh19/zabbix-vue#2]
In version 1.0.0 when I add details that do not authenticate me on the zabbix server, the icon in the extensions area remains green and reports no zabbix issues when clicked 
![zabbix-issue](https://user-images.githubusercontent.com/16209893/37458318-9fcae8cc-283c-11e8-8e74-39d73d1a7d32.jpg)

Ideally this would offer an authentication issue to the user so they know they need to look at their credentials.

**Comment by mchugh19** [comment]
Please try out the just released 1.0.4. I am unable to replicate.
