### ISSUE TITLE
Doesnt work on Firefox 63

### ISSUE THREAD

**Issue by mirhosting** [mchugh19/zabbix-vue#20]
Thank you for great plugin!
Unfortunately after recent update of firefox to 63 version (Windows 64 bit) it stop working.

If you click on button on toolbar its saying:
_Check server configuration in extension options:_ 

However, its not possible to see any settings and options of the plugin.

**Comment by mchugh19** [comment]
I just checked with firefox 64, and everything looks okay. To access the options screen from Firefox, click the menu dropdown and go to Addons. From there on the left side of the page, you should select Extensions. This will show the installed browser extensions, and the Zabbix Vue item should be displayed. Next to the Zabbix Vue item should be an options button. This will open up the extension options and allow you to configure the extension. 

If that doesn't work for you, what are you experiencing? Is there some problem preventing the display the options screen?

**Comment by mirhosting** [comment]
Hi Christian,

Thanks for update. I just tried to removed plugin, close/open the browser and install it again. Then settings appear again.
So, no ideas what is wrong but at least it can be easily fixed.

**Comment by mchugh19** [comment]
Woo hoo! Glad to hear it. I'll close this out then as not reproducible, but if you run into problems in the future, please report them again. 

Thanks!
