### ISSUE TITLE
Doesn't work correctly on Firefox 62/63

### ISSUE THREAD

**Issue by RomanHuBoss** [mchugh19/zabbix-vue#23]
Hello! 

The plugin works well with FF 61.0.2 (32-bit, Win), but, unfortunately, it doesn't work correctly neither with FF 62.0 (64x, Win), nor with the latest FF 63.0.3 (x64, Win). Thus, the first one presents Zabbix Vue notification popup when some event happens at Zabbix server, but last two browsers demonstrate "no problem".

All settings are the same. 

P.s. Thanks for your plugin. It's really essential.

**Comment by mchugh19** [comment]
Hey @RomanHuBoss. I'm unable to replicate. I've just installed Firefox developer edition 67.0b4 64-bit, and connecting to a Zabbix server appears to work.

![image](https://user-images.githubusercontent.com/1360357/55624642-80de1c80-579e-11e9-8768-59be3a58ba7c.png)

Are you still experiencing problems?

**Comment by RomanHuBoss** [comment]
No. Thanks. The problem resolved itself somehow.
