### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by heshammhafez** [mchugh19/zabbix-vue#26]
Thanks a lot for the effort and it will be really great if it has a sound notification like nagstatmon.
I hope to see it in coming updates.

**Comment by mchugh19** [comment]
Glad it's helpful for you!
Addressed in #27

**Comment by heshammhafez** [comment]
Thanks again for the update and fast reaction, I wondering if is it possible the change the dripping sound, I thought about changing the file under sound/drip.mp3 but I couldn't find it in my local pc I really don't know how firefox extensions work. BTW I'm using fedora 30.
