### ISSUE TITLE
Firefox 92.0 problem

### ISSUE THREAD

**Issue by mclarkson** [mchugh19/zabbix-vue#41]
Hi! I just upgraded to Firefox 92.0 on Linux but now Zabbix Vue reports "No configuration"

The preferences pane is empty.
Uninstalled and re-installed and the preferences pane is still completely blank with no buttons etc.

Thanks for this extension - it's been working fine for months before this Browser upgrade.

**Comment by mclarkson** [comment]
I have no idea why, but this add-on works again.

**Comment by mchugh19** [comment]
Thanks @mclarkson. I was having a hard time replicating. 

Generally, these sorts of wacky issues seem to come up with a long running browser session, and clear out when the browser is restarted. But I assume you restarted your browser a few times before it started working?

**Comment by mclarkson** [comment]
I'm using exactly the same firefox version as before and I uninstalled/reinstalled the extension. Maybe I didn't restart the browser, but I'm not sure now. Just very happy that it works again!
If this happens again I'll be sure to restart the browser! Sorry for the duff report and thanks for checking it out.
