### ISSUE TITLE
Popup table reorders aren't saved

### ISSUE THREAD

**Issue by xenadmin** [mchugh19/zabbix-vue#6]
For example, if I sort my Trigger Events by age, the next time I open the pop-up it's again sorted by default (priority)
Is there a chance to change this?

**Comment by swk** [comment]
yes this I've noticed this same behavior and was looking for where to save the default sort ordering. maybe this could be made an option on the config menu

**Comment by mchugh19** [comment]
Hey all. This is resolved and will be in the next release. Changes to the sorting of popup headers are now saved.
