### ISSUE TITLE
After update plugin to 2.1.0 show error

### ISSUE THREAD

**Issue by freejoins** [mchugh19/zabbix-vue#60]
After update plugin to 2.1.0 version in Chrome 111.0.5563.65 on Windows 11 i see error:

> {"code":-32602,"message":"Invalid params.","data":"Invalid parameter \"/\": unexpected parameter \"username\"."}

Zabbix server Version: 4.0.44

**Comment by sparkssssssss** [comment]
version 3.4.10 also doesn't work any more ,show error below
> Uncaught (in promise) Error: {"code":-32602,"message":"Invalid params.","data":"Not authorised."}

**Comment by aceslup** [comment]
Zabbix server Version: 5.0.21, same

**Comment by mchugh19** [comment]
Apologies everyone. There was a problem with the version number parsing, which ended up using the newer API format on older servers. This was corrected in 2.1.1, which was just released to the firefox and chrome repos.

**Comment by aceslup** [comment]
thanks 👍
