### ISSUE TITLE
Zabbix Vue 2.1.1 does not function with Zabbix 6.4.2

### ISSUE THREAD

**Issue by JeffZwolle** [mchugh19/zabbix-vue#63]
Zabbix Vue 2.1.1 in Google Chrome browser (Windows) does not function with Zabbix 6.4.2
The problem is that the indicator stays black. And an even bigger problem is that my login session in another browser is closed after about 5 to 10 seconds, meaning that I have to login there again and being logged out again after 5 to 10 seconds. The extension worked fine before I upgraded from Zabbix 6.0

**Comment by Matsumot0** [comment]
Hello,

Same here :(

**Comment by Dainii** [comment]
@JeffZwolle Are you using authentication with token auth ? If not, you should switch to that. It's the new "right way" to query the API. I have no issues with multiple Zabbix 6.4.3.

**Comment by Matsumot0** [comment]
@Dainii Thanks for the tip, it's works great via token api :)

**Comment by JeffZwolle** [comment]
@Dainii 
Yes, that functions.
Thank you very much!
