### ISSUE TITLE
Frontend with Zabbix 2.0.9 does not work

### ISSUE THREAD

**Issue by simonTIG** [mchugh19/zabbix-vue#7]
Hi,

We are still running Zabbix version 2.0.9 (planning to change this year) and the connection does not work correctly. I've entered all the correct parameters in the options and I see a popup alert with the latest trigger, but the frontend does not work and says: Check server configuration in extension options: Error communicating with: https://zabbixurl
![2018-03-21_08-29-31](https://user-images.githubusercontent.com/33513526/37698280-497011fa-2ce2-11e8-828e-40370cef6a56.png)

It is the same error on both Chrome and Firefox.

I have tested with a newer version of zabbix on a VM and I don't have any issue.

Thanks a lot

**Comment by mchugh19** [comment]
I've just tested with Zabbix 2.2 (the oldest version they have a VM image for) and it appears to function properly. Zabbix 2.0 is no longer supported, and I am unable to locate an appliance download to test. Unfortunately, I think this means Zabbix 2.2 is the minimum supportable version.

**Comment by mchugh19** [comment]
Closing this out as I cannot find a 2.0 image to test against.
